### PR TITLE
4.20

### PR DESCRIPTION
**Pull request by ReneFGJr**
Send the new library of 4.20

### CODE REVIEW

**Comment by qqmyers** [comment]
@amberleahey , @JayanthyChengan , @bikramj , - you three are the only ones with admin rights on this repository right now. How do you want to handle PR requests like this one? Do you guys want to be merging them or should we give rights to people who submit them? Or?

**Comment by ReneFGJr** [comment]
Dear,

The our version could be merge.

Sds,

*Prof. Dr. Rene Faustino Gabriel Junior*
Universidade Federal do Rio Grande do Sul
r <renefgj@gmail.com>ene.gabriel@ufrgs.br | renefgj@gmail.com
Fone: 55(41)98811.9061
Lattes <http://lattes.cnpq.br/5900345665779424>| RiD
<http://www.researcherid.com/rid/E-3759-2013> | OrcID
<http://orcid.org/0000-0003-1021-3360> | LinkId
<https://br.linkedin.com/in/rene-faustino-gabriel-junior-bb62a718>





Em qui., 28 de mai. de 2020 às 11:55, qqmyers <notifications@github.com>
escreveu:

**Comment by bikramj** [comment]
@qqmyers my apologies I didn't notice this earlier. @JayanthyChengan Could you please take care of this PR and We can add people who should be able to merge in this repo.

**Comment by 4tikhonov** [comment]
Sorry, I've missed this PR. Please check if everything is fine.

**Pull request merged**
